FROM registry:2.7.1

ADD config.yml /etc/docker/registry/config.yml
ADD registry.crt /etc/docker/registry/certs/registry.crt
ADD registry.key /etc/docker/registry/certs/registry.key
ADD htpasswd /etc/docker/registry/htpasswd